/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador_AsignarServicio;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import controlador.conexion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VictorMTA
 */
public class Asignacion_Servicio extends javax.swing.JFrame {
 int fila=-1;

    controlador_AsignarServicio f = new controlador_AsignarServicio();  
     conexion con=new conexion();
     
     public void mostrarServicio(){
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"N_OT","fecha_inicio","hora_inicio","fecha_final","hora_final","dueño","Costo_total","estado","pieza1","cantidad1","pieza2","cantidad2","pieza3","cantidad3","pieza4","cantidad4","pieza5","cantidad5","pieza6","cantidad6","pieza7","cantidad7","mecanico_asig1","mecanico_asig2","mecanico_asig3","mecanico_asig4","idservicio","nombre_servicio","costo_servicio","id_vehiculo","placa"};  
        // se utiliza la funcion
        dtAut = f.getDatos();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        TablaAsignacionServiciosDatos.setModel(datos);
    }
     
     
     
     public void mostrarDatos(){
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"dueño","placa","nombre_servicio","fecha_inicio","hora_inicio","Marca del auto"};  
        // se utiliza la funcion
        dtAut = f.getDatos2();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        TablaAsignacionServicio.setModel(datos);
    }
      
    /**
     * Creates new form Servicio
     */
    public Asignacion_Servicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        TxtCodigoAuto = new javax.swing.JLabel();
        TxtCodigoServicio = new javax.swing.JLabel();
        TxtCodigoMecanico1 = new javax.swing.JLabel();
        TxtCodigoMecanico2 = new javax.swing.JLabel();
        TxtCodigoMecanico3 = new javax.swing.JLabel();
        TxtCodigoMecanico4 = new javax.swing.JLabel();
        TxtCodigoInventario1 = new javax.swing.JLabel();
        TxtCodigoInventario2 = new javax.swing.JLabel();
        TxtCodigoInventario3 = new javax.swing.JLabel();
        TxtCodigoInventario4 = new javax.swing.JLabel();
        TxtCodigoInventario5 = new javax.swing.JLabel();
        TxtCodigoInventario6 = new javax.swing.JLabel();
        TxtCodigoInventario7 = new javax.swing.JLabel();
        txtEstado_de_Servicio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAsignacionServiciosDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtDueño = new javax.swing.JTextField();
        txtServico = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMecanico1 = new javax.swing.JTextField();
        BtnAsignarVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAsignacionServicio = new javax.swing.JTable();
        BtnAsignarMeca1 = new javax.swing.JButton();
        BtnAsignarMeca2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jsCantidad1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        TxtRepuesto1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnRepuesto1 = new javax.swing.JButton();
        jsCantidad2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        TxtRepuesto2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnRepuesto3 = new javax.swing.JButton();
        jsCantidad3 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        TxtRepuesto3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BtnRepuesto2 = new javax.swing.JButton();
        jsCantidad4 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        TxtRepuesto4 = new javax.swing.JTextField();
        BtnRepuesto5 = new javax.swing.JButton();
        jsCantidad5 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        TxtRepuesto5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BtnRepuesto4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        BtnRepuesto7 = new javax.swing.JButton();
        jsCantidad7 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        TxtRepuesto7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BtnRepuesto6 = new javax.swing.JButton();
        TxtRepuesto6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jsCantidad6 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        Folio = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        BtnAsignarMeca3 = new javax.swing.JButton();
        txtMecanico3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        BtnAsignarMeca4 = new javax.swing.JButton();
        txtMecanico2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtMecanico4 = new javax.swing.JTextField();
        BtnAsignarMeca5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtCostoAdicional = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();

        TxtCodigoAuto.setText("0");

        TxtCodigoServicio.setText("0");

        TxtCodigoMecanico1.setText("NULL");

        TxtCodigoMecanico2.setText("NULL");

        TxtCodigoMecanico3.setText("NULL");

        TxtCodigoMecanico4.setText("NULL");

        TxtCodigoInventario1.setText("NULL");

        TxtCodigoInventario2.setText("NULL");

        TxtCodigoInventario3.setText("NULL");

        TxtCodigoInventario4.setText("NULL");

        TxtCodigoInventario5.setText("NULL");

        TxtCodigoInventario6.setText("NULL");

        TxtCodigoInventario7.setText("NULL");

        txtEstado_de_Servicio.setText("1");

        TablaAsignacionServiciosDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaAsignacionServiciosDatos);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(TxtCodigoMecanico2)
                        .addGap(26, 26, 26)
                        .addComponent(TxtCodigoMecanico1))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(TxtCodigoMecanico3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtCodigoMecanico4)))
                .addGap(51, 51, 51)
                .addComponent(TxtCodigoServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCodigoAuto)
                .addGap(57, 57, 57)
                .addComponent(txtEstado_de_Servicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addComponent(TxtCodigoInventario5)
                            .addGap(18, 18, 18)
                            .addComponent(TxtCodigoInventario6))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addComponent(TxtCodigoInventario2)
                            .addGap(18, 18, 18)
                            .addComponent(TxtCodigoInventario4))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addComponent(TxtCodigoInventario1)
                            .addGap(18, 18, 18)
                            .addComponent(TxtCodigoInventario3)))
                    .addComponent(TxtCodigoInventario7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(TxtCodigoInventario7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigoInventario5)
                    .addComponent(TxtCodigoInventario6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigoMecanico3)
                    .addComponent(TxtCodigoMecanico4)
                    .addComponent(TxtCodigoInventario1)
                    .addComponent(TxtCodigoInventario3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigoAuto)
                    .addComponent(TxtCodigoServicio)
                    .addComponent(TxtCodigoMecanico1)
                    .addComponent(TxtCodigoMecanico2)
                    .addComponent(TxtCodigoInventario2)
                    .addComponent(TxtCodigoInventario4)
                    .addComponent(txtEstado_de_Servicio))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("RomanT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servicio");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Vehiculo:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Dueño:");

        txtPlaca.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtPlaca.setBorder(null);
        txtPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtDueño.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtDueño.setBorder(null);
        txtDueño.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueñoActionPerformed(evt);
            }
        });

        txtServico.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtServico.setBorder(null);
        txtServico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });

        txtCosto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtCosto.setBorder(null);
        txtCosto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Servicio:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Costo:");

        txtMecanico1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtMecanico1.setBorder(null);
        txtMecanico1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMecanico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMecanico1ActionPerformed(evt);
            }
        });

        BtnAsignarVehiculo.setText("Asignar");
        BtnAsignarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarVehiculoActionPerformed(evt);
            }
        });

        TablaAsignacionServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaAsignacionServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsignacionServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAsignacionServicio);

        BtnAsignarMeca1.setText("Asignar");
        BtnAsignarMeca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarMeca1ActionPerformed(evt);
            }
        });

        BtnAsignarMeca2.setText("Asignar");
        BtnAsignarMeca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarMeca2ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad:");

        TxtRepuesto1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto1.setBorder(null);
        TxtRepuesto1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Repuesto 1:");

        BtnRepuesto1.setText("Seleccionar ");
        BtnRepuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad:");

        TxtRepuesto2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto2.setBorder(null);
        TxtRepuesto2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Repuesto 2:");

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Repuesto 4:");

        BtnRepuesto3.setText("Seleccionar ");
        BtnRepuesto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Cantidad:");

        TxtRepuesto3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto3.setBorder(null);
        TxtRepuesto3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Repuesto 3:");

        BtnRepuesto2.setText("Seleccionar ");
        BtnRepuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Cantidad:");

        TxtRepuesto4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto4.setBorder(null);
        TxtRepuesto4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto4ActionPerformed(evt);
            }
        });

        BtnRepuesto5.setText("Seleccionar ");
        BtnRepuesto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto5ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Cantidad:");

        TxtRepuesto5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto5.setBorder(null);
        TxtRepuesto5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Repuesto 5:");

        BtnRepuesto4.setText("Seleccionar ");
        BtnRepuesto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Agency FB", 2, 18)); // NOI18N
        jLabel18.setText("Repuestos Extras");

        BtnRepuesto7.setText("Seleccionar ");
        BtnRepuesto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel19.setText("Cantidad:");

        TxtRepuesto7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto7.setBorder(null);
        TxtRepuesto7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto7ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel20.setText("Repuesto 7:");

        BtnRepuesto6.setText("Seleccionar ");
        BtnRepuesto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto6ActionPerformed(evt);
            }
        });

        TxtRepuesto6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto6.setBorder(null);
        TxtRepuesto6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto6ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel21.setText("Repuesto 6:");

        jLabel22.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel22.setText("Cantidad:");

        Folio.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        Folio.setText("Folio");

        Fecha.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        Fecha.setText("Fecha");

        Hora.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        Hora.setText("Hora");

        btnBuscar.setText("Nuevo Auto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtBuscar.setBorder(null);
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Iniciar Reparacion");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 102, 204));
        btnIngresar.setText("Ingresar Auto");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        jLabel27.setText("Mecanico1:");

        BtnAsignarMeca3.setText("Asignar");
        BtnAsignarMeca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarMeca3ActionPerformed(evt);
            }
        });

        txtMecanico3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtMecanico3.setBorder(null);
        txtMecanico3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMecanico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMecanico3ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        jLabel28.setText("Mecanico3:");

        BtnAsignarMeca4.setText("Asignar");
        BtnAsignarMeca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarMeca4ActionPerformed(evt);
            }
        });

        txtMecanico2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtMecanico2.setBorder(null);
        txtMecanico2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMecanico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMecanico2ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        jLabel29.setText("Mecanico3:");

        txtMecanico4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtMecanico4.setBorder(null);
        txtMecanico4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMecanico4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMecanico4ActionPerformed(evt);
            }
        });

        BtnAsignarMeca5.setText("Asignar");
        BtnAsignarMeca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarMeca5ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        jLabel30.setText("Mecanico2:");

        txtCostoAdicional.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtCostoAdicional.setBorder(null);
        txtCostoAdicional.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCostoAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoAdicionalActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        jLabel31.setText("Costo Adicional:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Folio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(114, 114, 114)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtnAsignarVehiculo)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnAsignarMeca2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCostoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMecanico3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnAsignarMeca3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMecanico1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnAsignarMeca1)
                                                .addGap(276, 276, 276)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMecanico4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnAsignarMeca5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMecanico2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnAsignarMeca4)
                                                .addGap(276, 276, 276))))))
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscar)
                                .addGap(439, 439, 439))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto7))
                            .addComponent(jsCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtRepuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jsCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtRepuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jsCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TxtRepuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jsCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TxtRepuesto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jsCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TxtRepuesto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jsCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(TxtRepuesto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TxtRepuesto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Folio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fecha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hora)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(BtnAsignarVehiculo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAsignarMeca2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCostoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMecanico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAsignarMeca3)
                                    .addComponent(jLabel28)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMecanico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnAsignarMeca1)
                                .addComponent(jLabel27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMecanico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAsignarMeca5)
                                    .addComponent(jLabel29)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMecanico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAsignarMeca4)
                                    .addComponent(jLabel30))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnSalir))
                .addContainerGap())
            .addComponent(jSeparator2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueñoActionPerformed

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtMecanico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMecanico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMecanico1ActionPerformed

    private void BtnAsignarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarVehiculoActionPerformed
  new Automovil().setVisible(true);
        Automovil.opcAutomovil = 1;

        Automovil.VerificaAuto.setText("1");

    }//GEN-LAST:event_BtnAsignarVehiculoActionPerformed

    private void BtnAsignarMeca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarMeca1ActionPerformed
new ListaMecanicos().setVisible(true);
        ListaMecanicos.opcMecanicos = 1;

        ListaMecanicos.VerificaMecanico.setText("1");

        
    }//GEN-LAST:event_BtnAsignarMeca1ActionPerformed

    private void BtnAsignarMeca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarMeca2ActionPerformed
 new Servicio().setVisible(true);
        Servicio.opcServicio = 1;

        Servicio.VerificaServicio.setText("1");


        
    }//GEN-LAST:event_BtnAsignarMeca2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  String Fecha_inicio,Fecha_final;
    Calendar Cal= Calendar.getInstance();     
        
       String spinner1 = jsCantidad1.getValue().toString();
       String spinner2 = jsCantidad2.getValue().toString();
       String spinner3 = jsCantidad3.getValue().toString();
       String spinner4 = jsCantidad4.getValue().toString();
       String spinner5 = jsCantidad5.getValue().toString();
       String spinner6 = jsCantidad6.getValue().toString();
       String spinner7 = jsCantidad7.getValue().toString();
   
//RESTAMOS LA CANTIDAD DE LOS ESPINNER EN LA LA TABLA DE REPUESTOS DE LA BD

 
       Fecha_inicio=Fecha.getText();//"   "+Cal.get(Cal.HOUR_OF_DAY)+ ":"+Cal.get(Cal.MINUTE);
       String hora_inicio=Hora.getText();
       Fecha_final= null;//"   "+Cal.get(Cal.HOUR_OF_DAY)+ ":"+Cal.get(Cal.MINUTE);
       String hora_final=null;
       String Nombre_servicio=txtServico.getText();
       String Placa_vehiculo=txtPlaca.getText();
       String dueño=txtDueño.getText();
       double Costo_total=Double.parseDouble(txtCosto.getText());
       int estado= Integer.parseInt(txtEstado_de_Servicio.getText());
       
       ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS REPUESTOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
         String Repuesto1=TxtRepuesto1.getText();
        if(TxtRepuesto1.getText().length()==0){
            Repuesto1=null; 
        }else{
            Repuesto1=TxtRepuesto1.getText();}
        
        String Repuesto2=TxtRepuesto2.getText();
        if(TxtRepuesto2.getText().length()==0){
            Repuesto2=null;
        }else{
            Repuesto2=TxtRepuesto2.getText();}
        
        String Repuesto3=TxtRepuesto3.getText();
        if(TxtRepuesto3.getText().length()==0){
            Repuesto3=null;
        }else{
            Repuesto3=TxtRepuesto3.getText();}
        
        String Repuesto4=TxtRepuesto4.getText();
        if(TxtRepuesto4.getText().length()==0){
            Repuesto4=null;
        }else{
            Repuesto4=TxtRepuesto4.getText();}
        
        String Repuesto5=TxtRepuesto5.getText();
        if(TxtRepuesto5.getText().length()==0){
            Repuesto5=null;
       }else{
            Repuesto5=TxtRepuesto5.getText();}
        
        String Repuesto6=TxtRepuesto6.getText();
        if(TxtRepuesto6.getText().length()==0){
            Repuesto6=null;
        }else{
            Repuesto6=TxtRepuesto6.getText();}
        
        String Repuesto7=TxtRepuesto7.getText();
        if(TxtRepuesto7.getText().length()==0){
            Repuesto7=null;
        }else{
            Repuesto7=TxtRepuesto7.getText();}
       
       
       
       
       int cantidad1=Integer.parseInt(spinner1);    
       int cantidad2=Integer.parseInt(spinner2);
       int cantidad3=Integer.parseInt(spinner3);
       int cantidad4=Integer.parseInt(spinner4);
       int cantidad5=Integer.parseInt(spinner5);
       int cantidad6=Integer.parseInt(spinner6);
       int cantidad7=Integer.parseInt(spinner7);
       
       ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS MECANICOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
       
       String mecanico_asig1=txtMecanico1.getText();
        if(txtMecanico1.getText().length()==0){
            mecanico_asig1=null;
        }else{
            mecanico_asig1=txtMecanico1.getText();}
        
         String mecanico_asig2=txtMecanico2.getText();
        if(txtMecanico2.getText().length()==0){
            mecanico_asig2=null;
        }else{
            mecanico_asig2=txtMecanico2.getText();}
        
         String mecanico_asig3=txtMecanico3.getText();
        if(txtMecanico3.getText().length()==0){
            mecanico_asig3=null;
        }else{
            mecanico_asig3=txtMecanico3.getText();}
        
         String mecanico_asig4=txtMecanico4.getText();
        if(txtMecanico4.getText().length()==0){
            mecanico_asig4=null;
        }else{
            mecanico_asig4=txtMecanico4.getText();}
       
        
//       f.nuevaAsignacion(Fecha_inicio,hora_inicio,null,null,id_servicio,id_vehiculo,dueño,Costo_total,estado,null,null,null,null,null,null,null,null,null,null,null,null,null,null,mecanico_asig1,null,null,null);
       
       f.nuevaAsignacion(Fecha_inicio,hora_inicio,null,null,Nombre_servicio,Placa_vehiculo,dueño,Costo_total,estado,Repuesto1,cantidad1,Repuesto2,cantidad2,Repuesto3,cantidad3,Repuesto4,cantidad4,Repuesto5,cantidad5,Repuesto6,cantidad6,Repuesto7,cantidad7,mecanico_asig1,mecanico_asig2,mecanico_asig3,mecanico_asig4);
        //id_cliente, nombre1, apellido_P2, apellido_M3, telefono4, TIF5, Email6, colonia7, calle8, no9, fecha10, hora11 
        //mostrarusuario();
       
        JOptionPane.showMessageDialog(rootPane,"Cliente ingresado");
       

       
        mostrarServicio();
        mostrarDatos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String folio = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 0));

        f.eliminarAsignacion(folio);
        
        mostrarServicio();
        mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
String Fecha_inicio,Fecha_final;
    Calendar Cal= Calendar.getInstance();     
        
       String spinner1 = jsCantidad1.getValue().toString();
       String spinner2 = jsCantidad2.getValue().toString();
       String spinner3 = jsCantidad3.getValue().toString();
       String spinner4 = jsCantidad4.getValue().toString();
       String spinner5 = jsCantidad5.getValue().toString();
       String spinner6 = jsCantidad6.getValue().toString();
       String spinner7 = jsCantidad7.getValue().toString();
   

       Fecha_inicio=Fecha.getText();//"   "+Cal.get(Cal.HOUR_OF_DAY)+ ":"+Cal.get(Cal.MINUTE);
       String hora_inicio=Hora.getText();
       Fecha_final= null;//"   "+Cal.get(Cal.HOUR_OF_DAY)+ ":"+Cal.get(Cal.MINUTE);
       String hora_final=null;
       String Nombre_servicio=txtServico.getText();
       String Placa_vehiculo=txtPlaca.getText();
       String dueño=txtDueño.getText();
       double Costo_total=Double.parseDouble(txtCosto.getText());
       int estado= Integer.parseInt(txtEstado_de_Servicio.getText());
       
       ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS REPUESTOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
         String Repuesto1=TxtRepuesto1.getText();
        if(TxtRepuesto1.getText().length()==0){
            Repuesto1=null; 
        }else{
            Repuesto1=TxtRepuesto1.getText();}
        
        String Repuesto2=TxtRepuesto2.getText();
        if(TxtRepuesto2.getText().length()==0){
            Repuesto2=null;
        }else{
            Repuesto2=TxtRepuesto2.getText();}
        
        String Repuesto3=TxtRepuesto3.getText();
        if(TxtRepuesto3.getText().length()==0){
            Repuesto3=null;
        }else{
            Repuesto3=TxtRepuesto3.getText();}
        
        String Repuesto4=TxtRepuesto4.getText();
        if(TxtRepuesto4.getText().length()==0){
            Repuesto4=null;
        }else{
            Repuesto4=TxtRepuesto4.getText();}
        
        String Repuesto5=TxtRepuesto5.getText();
        if(TxtRepuesto5.getText().length()==0){
            Repuesto5=null;
       }else{
            Repuesto5=TxtRepuesto5.getText();}
        
        String Repuesto6=TxtRepuesto6.getText();
        if(TxtRepuesto6.getText().length()==0){
            Repuesto6=null;
        }else{
            Repuesto6=TxtRepuesto6.getText();}
        
        String Repuesto7=TxtRepuesto7.getText();
        if(TxtRepuesto7.getText().length()==0){
            Repuesto7=null;
        }else{
            Repuesto7=TxtRepuesto7.getText();}
       
       
       
       
       int cantidad1=Integer.parseInt(spinner1);    
       int cantidad2=Integer.parseInt(spinner2);
       int cantidad3=Integer.parseInt(spinner3);
       int cantidad4=Integer.parseInt(spinner4);
       int cantidad5=Integer.parseInt(spinner5);
       int cantidad6=Integer.parseInt(spinner6);
       int cantidad7=Integer.parseInt(spinner7);
       
       ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS MECANICOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
       
       String mecanico_asig1=txtMecanico1.getText();
        if(txtMecanico1.getText().length()==0){
            mecanico_asig1=null;
        }else{
            mecanico_asig1=txtMecanico1.getText();}
        
         String mecanico_asig2=txtMecanico2.getText();
        if(txtMecanico2.getText().length()==0){
            mecanico_asig2=null;
        }else{
            mecanico_asig2=txtMecanico2.getText();}
        
         String mecanico_asig3=txtMecanico3.getText();
        if(txtMecanico3.getText().length()==0){
            mecanico_asig3=null;
        }else{
            mecanico_asig3=txtMecanico3.getText();}
        
         String mecanico_asig4=txtMecanico4.getText();
        if(txtMecanico4.getText().length()==0){
            mecanico_asig4=null;
        }else{
            mecanico_asig4=txtMecanico4.getText();}
        
//       int folio=Integer.parseInt(Folio.getText());
      int folio=Integer.parseInt(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 0)));
    
              f.ActualizarAsignar_servicio(Fecha_inicio,hora_inicio,null,null,Nombre_servicio,Placa_vehiculo,dueño,Costo_total,estado,Repuesto1,cantidad1,Repuesto2,cantidad2,Repuesto3,cantidad3,Repuesto4,cantidad4,Repuesto5,cantidad5,Repuesto6,cantidad6,Repuesto7,cantidad7,mecanico_asig1,mecanico_asig2,mecanico_asig3,mecanico_asig4,folio);

       JOptionPane.showMessageDialog(rootPane,"Asignacion Actualizado");
       

       
        mostrarServicio();
        mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();
    new Inicio().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void BtnAsignarMeca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarMeca3ActionPerformed
     new ListaMecanicos().setVisible(true);
        ListaMecanicos.opcMecanicos = 3;

        ListaMecanicos.VerificaMecanico.setText("1");

    }//GEN-LAST:event_BtnAsignarMeca3ActionPerformed

    private void txtMecanico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMecanico3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMecanico3ActionPerformed

    private void BtnAsignarMeca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarMeca4ActionPerformed
 
new ListaMecanicos().setVisible(true);
        ListaMecanicos.opcMecanicos = 2;

        ListaMecanicos.VerificaMecanico.setText("1");
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnAsignarMeca4ActionPerformed

    private void txtMecanico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMecanico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMecanico2ActionPerformed

    private void txtMecanico4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMecanico4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMecanico4ActionPerformed

    private void BtnAsignarMeca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarMeca5ActionPerformed
       new ListaMecanicos().setVisible(true);
        ListaMecanicos.opcMecanicos = 4;

        ListaMecanicos.VerificaMecanico.setText("1");

    }//GEN-LAST:event_BtnAsignarMeca5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Calendar Cal= Calendar.getInstance();
        String fecha= Cal.get (Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+ "/"+Cal.get(Cal.YEAR);//"   "+Cal.get(Cal.HOUR_OF_DAY)+ ":"+Cal.get(Cal.MINUTE);
        int hora1=Cal.get(Cal.HOUR_OF_DAY);
        int minutos=Cal.get(Cal.MINUTE);
        String hora = null;
   if(hora1>=12&&hora1<24){
               hora=Cal.get(Cal.HOUR)+ ":"+Cal.get(Cal.MINUTE)+" PM";
   }else if((hora1>=24^minutos>=00&&minutos<=59)&&hora1<12){
       hora=Cal.get(Cal.HOUR)+ ":"+Cal.get(Cal.MINUTE)+" AM";
   }
        Fecha.setText(fecha);
        Hora.setText(hora);

        //System.out.print(TxtCodigoMecanico1.getText());
        
//        System.out.print(hora1);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txtCostoAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoAdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoAdicionalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mostrarServicio();
mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void TablaAsignacionServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsignacionServicioMouseClicked
fila = TablaAsignacionServicio.rowAtPoint(evt.getPoint());

         if (fila > -1){                          
             Folio.setText(String.valueOf("Folio: "+TablaAsignacionServiciosDatos.getValueAt(fila, 0)));
             txtDueño.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 5)));
             txtCosto.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 6)));
           
            //vaciamos las cajas de texto de los repuestos en caso de que la BD devuelva nullo
            if(TablaAsignacionServiciosDatos.getValueAt(fila, 8)==null){  
               TxtRepuesto1.setText("");
                jsCantidad1.setValue(0);
             }else{
                 TxtRepuesto1.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 8)));
                String cantidad1 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 9));
                int Cantidad1 = Integer.parseInt(cantidad1);
                jsCantidad1.setValue(Cantidad1);
             }
            
            if(TablaAsignacionServiciosDatos.getValueAt(fila, 10)==null){  
               TxtRepuesto2.setText("");
               jsCantidad2.setValue(0);
             }else{
                 TxtRepuesto2.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 10)));
                String cantidad2 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 11));
                int Cantidad2 = Integer.parseInt(cantidad2);
             jsCantidad2.setValue(Cantidad2);
             }
            
             if (TablaAsignacionServiciosDatos.getValueAt(fila, 12) == null) {
                 TxtRepuesto3.setText("");
                 jsCantidad3.setValue(0);
             } else {
                 TxtRepuesto3.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 12)));
                 String cantidad3 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 13));
                 int Cantidad3 = Integer.parseInt(cantidad3);
                 jsCantidad3.setValue(Cantidad3);
             }

             if(TablaAsignacionServiciosDatos.getValueAt(fila, 14)==null){  
               TxtRepuesto4.setText("");
               jsCantidad4.setValue(0);
             }else{
                 TxtRepuesto4.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 14)));
                 String cantidad4 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 15));
                 int Cantidad4 = Integer.parseInt(cantidad4);
                 jsCantidad4.setValue(Cantidad4);
             }
             
             if(TablaAsignacionServiciosDatos.getValueAt(fila, 16)==null){  
               TxtRepuesto5.setText("");
               jsCantidad5.setValue(0);
             }else{
                 TxtRepuesto5.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 16)));
                 String cantidad5 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 17));
                 int Cantidad5 = Integer.parseInt(cantidad5);
                 jsCantidad5.setValue(Cantidad5);
             }
             
             if(TablaAsignacionServiciosDatos.getValueAt(fila, 18)==null){  
               TxtRepuesto6.setText("");
               jsCantidad6.setValue(0);
             }else{
                 TxtRepuesto6.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 18))); 
                 String cantidad6 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 19));
                 int Cantidad6 = Integer.parseInt(cantidad6);
                 jsCantidad6.setValue(Cantidad6);
             }
             
             if(TablaAsignacionServiciosDatos.getValueAt(fila, 20)==null){  
               TxtRepuesto7.setText("");
               jsCantidad7.setValue(0);
             }else{
                 TxtRepuesto7.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 20)));
                 String cantidad7 = String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 21));
                 int Cantidad7 = Integer.parseInt(cantidad7);
                 jsCantidad7.setValue(Cantidad7);
             }
             
             //damos condicion a las cajas de texto de los mecanicos sin en caso de que nos regrese null
             
              if(TablaAsignacionServiciosDatos.getValueAt(fila, 22)==null){  
               txtMecanico1.setText("");           
             }else{
                 txtMecanico1.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 22)));             
             }
           
             if (TablaAsignacionServiciosDatos.getValueAt(fila, 23) == null) {
                 txtMecanico2.setText("");
             } else {
                 txtMecanico2.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 23)));
             }
                 
             if (TablaAsignacionServiciosDatos.getValueAt(fila, 24) == null) {
                 txtMecanico3.setText("");
             } else {
                 txtMecanico3.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 24)));
             }
              
            if (TablaAsignacionServiciosDatos.getValueAt(fila, 25) == null) {
                 txtMecanico4.setText("");
             } else {
                 txtMecanico4.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 25)));
             }
             
             
             TxtCodigoServicio.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 26)));
             txtServico.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 27)));
             txtCosto.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 28)));
             TxtCodigoAuto.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 29)));
             txtPlaca.setText(String.valueOf(TablaAsignacionServiciosDatos.getValueAt(fila, 30)));
          
             
           
             
            
             
            
             

         }


      
    }//GEN-LAST:event_TablaAsignacionServicioMouseClicked

    private void BtnRepuesto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto4ActionPerformed

        new inventario().setVisible(true);
        inventario.opc = 14;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto4ActionPerformed

    private void TxtRepuesto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto5ActionPerformed

    private void BtnRepuesto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto5ActionPerformed
        new inventario().setVisible(true);
        inventario.opc = 15;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto5ActionPerformed

    private void TxtRepuesto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto4ActionPerformed

    private void BtnRepuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto2ActionPerformed
        new inventario().setVisible(true);
        inventario.opc = 12;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto2ActionPerformed

    private void TxtRepuesto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto3ActionPerformed

    private void BtnRepuesto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto3ActionPerformed
        new inventario().setVisible(true);
        inventario.opc = 13;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto3ActionPerformed

    private void TxtRepuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto2ActionPerformed

    private void BtnRepuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto1ActionPerformed

        new inventario().setVisible(true);
        inventario.opc = 11;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto1ActionPerformed

    private void TxtRepuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto1ActionPerformed

    private void TxtRepuesto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto6ActionPerformed

    private void BtnRepuesto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto6ActionPerformed
        new inventario().setVisible(true);
        inventario.opc = 16;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto6ActionPerformed

    private void TxtRepuesto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto7ActionPerformed

    }//GEN-LAST:event_TxtRepuesto7ActionPerformed

    private void BtnRepuesto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto7ActionPerformed
        new inventario().setVisible(true);
        inventario.opc = 17;

        inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignacion_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignacion_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignacion_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignacion_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignacion_Servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsignarMeca1;
    private javax.swing.JButton BtnAsignarMeca2;
    private javax.swing.JButton BtnAsignarMeca3;
    private javax.swing.JButton BtnAsignarMeca4;
    private javax.swing.JButton BtnAsignarMeca5;
    private javax.swing.JButton BtnAsignarVehiculo;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnRepuesto1;
    private javax.swing.JButton BtnRepuesto2;
    private javax.swing.JButton BtnRepuesto3;
    private javax.swing.JButton BtnRepuesto4;
    private javax.swing.JButton BtnRepuesto5;
    private javax.swing.JButton BtnRepuesto6;
    private javax.swing.JButton BtnRepuesto7;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Folio;
    private javax.swing.JLabel Hora;
    private javax.swing.JTable TablaAsignacionServicio;
    private javax.swing.JTable TablaAsignacionServiciosDatos;
    public static javax.swing.JLabel TxtCodigoAuto;
    public static javax.swing.JLabel TxtCodigoInventario1;
    public static javax.swing.JLabel TxtCodigoInventario2;
    public static javax.swing.JLabel TxtCodigoInventario3;
    public static javax.swing.JLabel TxtCodigoInventario4;
    public static javax.swing.JLabel TxtCodigoInventario5;
    public static javax.swing.JLabel TxtCodigoInventario6;
    public static javax.swing.JLabel TxtCodigoInventario7;
    public static javax.swing.JLabel TxtCodigoMecanico1;
    public static javax.swing.JLabel TxtCodigoMecanico2;
    public static javax.swing.JLabel TxtCodigoMecanico3;
    public static javax.swing.JLabel TxtCodigoMecanico4;
    public static javax.swing.JLabel TxtCodigoServicio;
    public static javax.swing.JTextField TxtRepuesto1;
    public static javax.swing.JTextField TxtRepuesto2;
    public static javax.swing.JTextField TxtRepuesto3;
    public static javax.swing.JTextField TxtRepuesto4;
    public static javax.swing.JTextField TxtRepuesto5;
    public static javax.swing.JTextField TxtRepuesto6;
    public static javax.swing.JTextField TxtRepuesto7;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jsCantidad1;
    private javax.swing.JSpinner jsCantidad2;
    private javax.swing.JSpinner jsCantidad3;
    private javax.swing.JSpinner jsCantidad4;
    private javax.swing.JSpinner jsCantidad5;
    private javax.swing.JSpinner jsCantidad6;
    private javax.swing.JSpinner jsCantidad7;
    private javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtCosto;
    public static javax.swing.JTextField txtCostoAdicional;
    public static javax.swing.JTextField txtDueño;
    private javax.swing.JLabel txtEstado_de_Servicio;
    public static javax.swing.JTextField txtMecanico1;
    public static javax.swing.JTextField txtMecanico2;
    public static javax.swing.JTextField txtMecanico3;
    public static javax.swing.JTextField txtMecanico4;
    public static javax.swing.JTextField txtPlaca;
    public static javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
}
