/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.conexion;
import controlador.controlador_inventario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author VictorMTA
 */
public class inventario extends javax.swing.JFrame {
 public static int opc; 
    
    int fila=-1;
    //Constructor de Clase
     controlador_inventario f = new controlador_inventario();  
     conexion con=new conexion();
     
     
    public void mostrarInventario(){
//        switch(opc){
//            case 1:
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"id_pieza","codigo_pieza", "nombre", "marca", "costo_pieza", "catidad"};  
        // se utiliza la funcion
        dtAut = f.getDatos();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        Tabla_Invenatrio1.setModel(datos);
//        break;}
    }
     
    
     public void mostrarDatos(){
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"codigo_pieza", "nombre", "marca", "costo_pieza", "catidad"};  
        // se utiliza la funcion
        dtAut = f.getDatos2();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        TablaInventario.setModel(datos);
    }
    
    
    
    public inventario() {
        this.setLocation(350, 0);
        initComponents();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Invenatrio1 = new javax.swing.JTable();
        jCodigo = new javax.swing.JLabel();
        TxtVerficaVentana = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtMarcaProducto = new javax.swing.JTextField();
        Txtcosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jsCantidad = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtcodigoProducto = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Tabla_Invenatrio1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabla_Invenatrio1);

        jCodigo.setText("jLabel7");

        TxtVerficaVentana.setText("0");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtVerficaVentana)
                .addGap(71, 71, 71)
                .addComponent(jCodigo)
                .addGap(145, 145, 145))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCodigo)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtVerficaVentana)
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("RomanT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Inventario");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del producto:");

        TxtNombreProducto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtNombreProducto.setBorder(null);
        TxtNombreProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreProductoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Marca:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Costo:");

        TxtMarcaProducto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtMarcaProducto.setBorder(null);
        TxtMarcaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtMarcaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMarcaProductoActionPerformed(evt);
            }
        });

        Txtcosto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Txtcosto.setBorder(null);
        Txtcosto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Txtcosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcostoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad:");

        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaInventario);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Codigo del Producto:");

        TxtcodigoProducto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtcodigoProducto.setBorder(null);
        TxtcodigoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtcodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcodigoProductoActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtBuscar.setBorder(null);
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnInventario.setBackground(new java.awt.Color(0, 102, 204));
        BtnInventario.setText("Ingresar A Servicio");
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSalir)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnInventario)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreProductoActionPerformed

    private void TxtMarcaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMarcaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMarcaProductoActionPerformed

    private void TxtcostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcostoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         String Campo1, Campo2, Campo3;
         
       String spinner = jsCantidad.getValue().toString();
       
        Campo1=TxtcodigoProducto.getText();
        Campo2=TxtNombreProducto.getText();
        Campo3=TxtMarcaProducto.getText();
       double Campo4=Double.parseDouble(Txtcosto.getText());
       int Campo5=Integer.parseInt(spinner);
       
        f.nuevaPieza(Campo1, Campo2, Campo3, Campo4, Campo5);
        //id_cliente, nombre1, apellido_P2, apellido_M3, telefono4, TIF5, Email6, colonia7, calle8, no9, fecha10, hora11 
        //mostrarusuario();
       
        JOptionPane.showMessageDialog(rootPane,"Cliente ingresado");
        
       
        mostrarInventario();
mostrarDatos();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (fila > -1){
            String codigo = String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0));                        
            f.eliminarProducto(codigo);
            mostrarDatos();
            fila=-1;
        }
//mostrarDatos();
//mostrarInventario();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

String Campo1, Campo2, Campo3;
          
           int Campo6;   
       String codigo = String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0));                        
       String spinner = jsCantidad.getValue().toString();
       
        Campo1=TxtcodigoProducto.getText();
        Campo2=TxtNombreProducto.getText();
        Campo3=TxtMarcaProducto.getText();
        double Campo4 = Double.parseDouble(Txtcosto.getText());
        int Campo5 = Integer.parseInt(spinner);
         Campo6 = Integer.parseInt(codigo);

        f.ActualizarInventario(Campo1, Campo2, Campo3, Campo4, Campo5, Campo6);
         JOptionPane.showMessageDialog(rootPane,"producto actualizado");
         
//          TxtcodigoProducto
//        TxtNombreProducto
//        TxtMarcaProducto
//        Txtcosto  
        mostrarInventario();
mostrarDatos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TxtcodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcodigoProductoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mostrarInventario();
mostrarDatos();

    int VerficaVentana=Integer.parseInt(TxtVerficaVentana.getText());
if(VerficaVentana==1){
     this.BtnInventario.setVisible(true);
}else{
        this.BtnInventario.setVisible(false);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void TablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaInventarioMouseClicked
fila = TablaInventario.rowAtPoint(evt.getPoint());

         if (fila > -1){                          
             TxtcodigoProducto.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 1)));
             TxtNombreProducto.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
             TxtMarcaProducto.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 3)));
             Txtcosto.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 4)));
//             jsCantidad.setValue(String.valueOf(TablaInventario.getValueAt(fila, 5)));
String valorf=String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 5));
        int valido = Integer.parseInt(valorf);
        jsCantidad.setValue(valido);

         }


                
    }//GEN-LAST:event_TablaInventarioMouseClicked

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed

        switch(opc){
            case 1:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo1.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto1.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }
               Servicio.jcodigo1.setText(jCodigo.getText());
               Servicio.TxtRepuesto1.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza1.setText(Txtcosto.getText());
               Servicio.jsCantidad1.setValue(1);
               
  
            this.dispose();
            break;
            
            case 2:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo2.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto2.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                Servicio.jcodigo2.setText(jCodigo.getText());
               Servicio.TxtRepuesto2.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza2.setText(Txtcosto.getText()); 
               Servicio.jsCantidad2.setValue(1);
            this.dispose();
            break;
            
              case 3:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo3.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto3.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo3.setText(jCodigo.getText());
               Servicio.TxtRepuesto3.setText(TxtNombreProducto.getText());
               Servicio.CostoPieza3.setText(Txtcosto.getText()); 
               Servicio.jsCantidad3.setValue(1);
            this.dispose();
            break;
            
              case 4:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo4.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto4.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo4.setText(jCodigo.getText());
               Servicio.TxtRepuesto4.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza4.setText(Txtcosto.getText()); 
               Servicio.jsCantidad4.setValue(1);
            this.dispose();
            break;
            
              case 5:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo5.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto5.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo5.setText(jCodigo.getText());
               Servicio.TxtRepuesto5.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza5.setText(Txtcosto.getText()); 
               Servicio.jsCantidad5.setValue(1);
            this.dispose();
            break;
            
              case 6:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo6.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto6.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo6.setText(jCodigo.getText());
               Servicio.TxtRepuesto6.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza6.setText(Txtcosto.getText());
               Servicio.jsCantidad6.setValue(1);
            this.dispose();
            break;
            
              case 7:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo7.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto7.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo7.setText(jCodigo.getText());
               Servicio.TxtRepuesto7.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza7.setText(Txtcosto.getText()); 
               Servicio.jsCantidad7.setValue(1);
            this.dispose();
            break;
            
              case 8:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
//            if (fila > -1){
//               Servicio.jcodigo8.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
//               Servicio.TxtRepuesto8.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
//            }  
                  Servicio.jcodigo8.setText(jCodigo.getText());
               Servicio.TxtRepuesto8.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza8.setText(Txtcosto.getText()); 
               Servicio.jsCantidad8.setValue(1);
            this.dispose();
            break;
            
              case 9:
   
                  Servicio.jcodigo9.setText(jCodigo.getText());
               Servicio.TxtRepuesto9.setText(TxtNombreProducto.getText());
               Servicio.CostoPieza9.setText(Txtcosto.getText()); 
               Servicio.jsCantidad9.setValue(1);
            this.dispose();
            break;
            
              case 10:
                  Servicio.jcodigo10.setText(jCodigo.getText());
               Servicio.TxtRepuesto10.setText(TxtNombreProducto.getText()); 
               Servicio.CostoPieza10.setText(Txtcosto.getText()); 
               Servicio.jsCantidad10.setValue(1);
            this.dispose();
            break;
            
              case 11:
               Asignacion_Servicio.TxtCodigoInventario1.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto1.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
            
              case 12:
               Asignacion_Servicio.TxtCodigoInventario2.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto2.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
            
              case 13:
               Asignacion_Servicio.TxtCodigoInventario3.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto3.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
            
              case 14:
               Asignacion_Servicio.TxtCodigoInventario4.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto4.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
              case 15:
               Asignacion_Servicio.TxtCodigoInventario5.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto5.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
              case 16:
               Asignacion_Servicio.TxtCodigoInventario6.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto6.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
              case 17:
               Asignacion_Servicio.TxtCodigoInventario7.setText(jCodigo.getText());
               Asignacion_Servicio.TxtRepuesto7.setText(TxtNombreProducto.getText()); 
            this.dispose();
            break;
        }
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInventarioActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed

this.dispose();
    new Inicio().setVisible(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    public javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JTable Tabla_Invenatrio1;
    private javax.swing.JTextField TxtMarcaProducto;
    private javax.swing.JTextField TxtNombreProducto;
    public static javax.swing.JLabel TxtVerficaVentana;
    private javax.swing.JTextField TxtcodigoProducto;
    private javax.swing.JTextField Txtcosto;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jCodigo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner jsCantidad;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
