/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.conexion;
import controlador.controlador_Servicio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author VictorMTA
 */
public class Servicio extends javax.swing.JFrame {
int fila=-1;
public static int opcServicio;
    //Constructor de Clase
     controlador_Servicio f = new controlador_Servicio();  
     conexion con=new conexion();
     
     
    public void mostrarServicio(){
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"idservicio","nombre_servicio","costo_servicio","repuesto1","cantidad1","repuesto2","cantidad2","repuesto3","cantidad3","repuesto4","cantidad4","repuesto5","cantidad5","repuesto6","cantidad6","repuesto7","cantidad7","repuesto8","cantidad8","repuesto9","cantidad9","repuesto10","cantidad10","CostoSumado","costo1","costo2","costo3","costo4","costo5","costo6","costo7","costo8","costo9","costo10"};  
        // se utiliza la funcion
        dtAut = f.getDatos();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        TablaServicio1.setModel(datos);
    }
    
    public void mostrarDatos(){
        con.conectar();
        Object[][] dtAut;        
        String[] columNames = {"nombre_servicio","costo_servicio","Costo Total"};  
        // se utiliza la funcion
        dtAut = f.getDatos2();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtAut,columNames);                        
        TablaServicio.setModel(datos);
    }
     
    public Servicio() {
        this.setLocation(350, 0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaServicio1 = new javax.swing.JTable();
        jcodigo1 = new javax.swing.JLabel();
        jcodigo2 = new javax.swing.JLabel();
        jcodigo3 = new javax.swing.JLabel();
        jcodigo4 = new javax.swing.JLabel();
        jcodigo5 = new javax.swing.JLabel();
        jcodigo6 = new javax.swing.JLabel();
        jcodigo7 = new javax.swing.JLabel();
        jcodigo8 = new javax.swing.JLabel();
        jcodigo9 = new javax.swing.JLabel();
        jcodigo10 = new javax.swing.JLabel();
        VerificaServicio = new javax.swing.JLabel();
        TxtCodigoServicio = new javax.swing.JLabel();
        CostoPieza1 = new javax.swing.JLabel();
        CostoPieza2 = new javax.swing.JLabel();
        CostoPieza3 = new javax.swing.JLabel();
        CostoPieza4 = new javax.swing.JLabel();
        CostoPieza5 = new javax.swing.JLabel();
        CostoPieza6 = new javax.swing.JLabel();
        CostoPieza7 = new javax.swing.JLabel();
        CostoPieza8 = new javax.swing.JLabel();
        CostoPieza9 = new javax.swing.JLabel();
        CostoPieza10 = new javax.swing.JLabel();
        Costo_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCosto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRepuesto1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jsCantidad1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaServicio = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtnombreServicio = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnRepuesto1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        TxtRepuesto2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jsCantidad2 = new javax.swing.JSpinner();
        BtnRepuesto2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtRepuesto3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jsCantidad3 = new javax.swing.JSpinner();
        BtnRepuesto3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TxtRepuesto4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jsCantidad4 = new javax.swing.JSpinner();
        BtnRepuesto4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TxtRepuesto5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jsCantidad5 = new javax.swing.JSpinner();
        BtnRepuesto5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TxtRepuesto6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jsCantidad6 = new javax.swing.JSpinner();
        BtnRepuesto6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        TxtRepuesto7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jsCantidad7 = new javax.swing.JSpinner();
        BtnRepuesto7 = new javax.swing.JButton();
        BtnRepuesto8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        TxtRepuesto8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jsCantidad8 = new javax.swing.JSpinner();
        BtnRepuesto9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        TxtRepuesto9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jsCantidad9 = new javax.swing.JSpinner();
        BtnRepuesto10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        TxtRepuesto10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jsCantidad10 = new javax.swing.JSpinner();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TablaServicio1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaServicio1);

        jcodigo1.setText("NULL");

        jcodigo2.setText("NULL");

        jcodigo3.setText("NULL");

        jcodigo4.setText("NULL");

        jcodigo5.setText("NULL");

        jcodigo6.setText("NULL");

        jcodigo7.setText("NULL");

        jcodigo8.setText("NULL");

        jcodigo9.setText("NULL");

        jcodigo10.setText("NULL");

        VerificaServicio.setText("0");

        TxtCodigoServicio.setText("jLabel3");

        CostoPieza1.setText("0");

        CostoPieza2.setText("0");

        CostoPieza3.setText("0");

        CostoPieza4.setText("0");

        CostoPieza5.setText("0");

        CostoPieza6.setText("0");

        CostoPieza7.setText("0");

        CostoPieza8.setText("0");

        CostoPieza9.setText("0");

        CostoPieza10.setText("0");

        Costo_total.setText("0");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(VerificaServicio)
                .addGap(31, 31, 31)
                .addComponent(TxtCodigoServicio)
                .addGap(30, 30, 30)
                .addComponent(jcodigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcodigo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcodigo3)
                .addGap(18, 18, 18)
                .addComponent(jcodigo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcodigo5)
                .addGap(26, 26, 26)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jcodigo6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jcodigo7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcodigo8)
                            .addComponent(jcodigo9)
                            .addComponent(jcodigo10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addGap(0, 162, Short.MAX_VALUE)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Costo_total)
                            .addComponent(CostoPieza1))
                        .addGap(24, 24, 24))))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(653, Short.MAX_VALUE)
                    .addComponent(CostoPieza2)
                    .addGap(14, 14, 14)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(663, Short.MAX_VALUE)
                    .addComponent(CostoPieza3)
                    .addGap(4, 4, 4)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(657, Short.MAX_VALUE)
                    .addComponent(CostoPieza4)
                    .addContainerGap()))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(647, Short.MAX_VALUE)
                    .addComponent(CostoPieza5)
                    .addGap(20, 20, 20)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(657, Short.MAX_VALUE)
                    .addComponent(CostoPieza6)
                    .addContainerGap()))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(647, Short.MAX_VALUE)
                    .addComponent(CostoPieza7)
                    .addGap(20, 20, 20)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(657, Short.MAX_VALUE)
                    .addComponent(CostoPieza8)
                    .addContainerGap()))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(647, Short.MAX_VALUE)
                    .addComponent(CostoPieza9)
                    .addGap(20, 20, 20)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(657, Short.MAX_VALUE)
                    .addComponent(CostoPieza10)
                    .addContainerGap()))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(CostoPieza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Costo_total)
                        .addGap(51, 51, 51)
                        .addComponent(jcodigo10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcodigo9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcodigo8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcodigo7)
                .addGap(4, 4, 4)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodigo1)
                    .addComponent(jcodigo2)
                    .addComponent(jcodigo3)
                    .addComponent(jcodigo4)
                    .addComponent(jcodigo5)
                    .addComponent(jcodigo6)
                    .addComponent(VerificaServicio)
                    .addComponent(TxtCodigoServicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(CostoPieza2)
                    .addContainerGap(287, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(CostoPieza3)
                    .addContainerGap(277, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(CostoPieza4)
                    .addContainerGap(267, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(CostoPieza5)
                    .addContainerGap(257, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(CostoPieza6)
                    .addContainerGap(247, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(CostoPieza7)
                    .addContainerGap(237, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(CostoPieza8)
                    .addContainerGap(227, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(CostoPieza9)
                    .addContainerGap(217, Short.MAX_VALUE)))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(CostoPieza10)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("RomanT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Servicios");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Costo $:");

        TxtCosto.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtCosto.setBorder(null);
        TxtCosto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCostoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Repuesto 1:");

        TxtRepuesto1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto1.setBorder(null);
        TxtRepuesto1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad:");

        TablaServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaServicioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaServicio);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Registro");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Nombre del Servicio:");

        TxtnombreServicio.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtnombreServicio.setBorder(null);
        TxtnombreServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtnombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnombreServicioActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        txtBuscar.setBorder(null);
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnRepuesto1.setText("Seleccionar ");
        BtnRepuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Repuesto 2:");

        TxtRepuesto2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto2.setBorder(null);
        TxtRepuesto2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad:");

        BtnRepuesto2.setText("Seleccionar ");
        BtnRepuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Repuesto 3:");

        TxtRepuesto3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto3.setBorder(null);
        TxtRepuesto3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad:");

        BtnRepuesto3.setText("Seleccionar ");
        BtnRepuesto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Repuesto 4:");

        TxtRepuesto4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto4.setBorder(null);
        TxtRepuesto4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad:");

        BtnRepuesto4.setText("Seleccionar ");
        BtnRepuesto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Repuesto 5:");

        TxtRepuesto5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto5.setBorder(null);
        TxtRepuesto5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto5ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel14.setText("Cantidad:");

        BtnRepuesto5.setText("Seleccionar ");
        BtnRepuesto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Repuesto 6:");

        TxtRepuesto6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto6.setBorder(null);
        TxtRepuesto6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto6ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Cantidad:");

        BtnRepuesto6.setText("Seleccionar ");
        BtnRepuesto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto6ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Repuesto 7:");

        TxtRepuesto7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto7.setBorder(null);
        TxtRepuesto7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto7ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel18.setText("Cantidad:");

        BtnRepuesto7.setText("Seleccionar ");
        BtnRepuesto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto7ActionPerformed(evt);
            }
        });

        BtnRepuesto8.setText("Seleccionar ");
        BtnRepuesto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto8ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel19.setText("Repuesto 8:");

        TxtRepuesto8.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto8.setBorder(null);
        TxtRepuesto8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto8ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel20.setText("Cantidad:");

        BtnRepuesto9.setText("Seleccionar ");
        BtnRepuesto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto9ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel21.setText("Repuesto 9:");

        TxtRepuesto9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto9.setBorder(null);
        TxtRepuesto9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto9ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel22.setText("Cantidad:");

        BtnRepuesto10.setText("Seleccionar ");
        BtnRepuesto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepuesto10ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel23.setText("Repuesto 10:");

        TxtRepuesto10.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        TxtRepuesto10.setBorder(null);
        TxtRepuesto10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtRepuesto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepuesto10ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel24.setText("Cantidad:");

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 102, 204));
        btnIngresar.setText("Ingresar Auto");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtnombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(187, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnBuscar))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 86, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRepuesto9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtRepuesto10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnRepuesto10)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtRepuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jsCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtRepuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jsCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtRepuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jsCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtRepuesto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jsCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtRepuesto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jsCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtRepuesto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jsCantidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TxtRepuesto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(BtnRepuesto8)
                                    .addComponent(TxtRepuesto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jsCantidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jsCantidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(TxtRepuesto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jsCantidad9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(TxtRepuesto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRepuesto10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jsCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtnombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresar)
                            .addComponent(btnSalir))
                        .addGap(39, 39, 39)))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCostoActionPerformed

    private void TxtRepuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         String Campo1;
         //convetimos los valores del spinner en a String
       String spinner1 = jsCantidad1.getValue().toString();
       String spinner2 = jsCantidad2.getValue().toString();
       String spinner3 = jsCantidad3.getValue().toString();
       String spinner4 = jsCantidad4.getValue().toString();
       String spinner5 = jsCantidad5.getValue().toString();
       String spinner6 = jsCantidad6.getValue().toString();
       String spinner7 = jsCantidad7.getValue().toString();
       String spinner8 = jsCantidad8.getValue().toString();
       String spinner9 = jsCantidad9.getValue().toString();
       String spinner10 = jsCantidad10.getValue().toString();
       
      
       
        Campo1=TxtnombreServicio.getText();
        double Campo2=Double.parseDouble(TxtCosto.getText());
        
         ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS REPUESTOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
         String Repuesto1=TxtRepuesto1.getText();
        if(TxtRepuesto1.getText().length()==0){
            Repuesto1=null; 
        }else{
            Repuesto1=TxtRepuesto1.getText();}
        
        String Repuesto2=TxtRepuesto2.getText();
        if(TxtRepuesto2.getText().length()==0){
            Repuesto2=null;
        }else{
            Repuesto2=TxtRepuesto2.getText();}
        
        String Repuesto3=TxtRepuesto3.getText();
        if(TxtRepuesto3.getText().length()==0){
            Repuesto3=null;
        }else{
            Repuesto3=TxtRepuesto3.getText();}
        
        String Repuesto4=TxtRepuesto4.getText();
        if(TxtRepuesto4.getText().length()==0){
            Repuesto4=null;
        }else{
            Repuesto4=TxtRepuesto4.getText();}
        
        String Repuesto5=TxtRepuesto5.getText();
        if(TxtRepuesto5.getText().length()==0){
            Repuesto5=null;
       }else{
            Repuesto5=TxtRepuesto5.getText();}
        
        String Repuesto6=TxtRepuesto6.getText();
        if(TxtRepuesto6.getText().length()==0){
            Repuesto6=null;
        }else{
            Repuesto6=TxtRepuesto6.getText();}
        
        String Repuesto7=TxtRepuesto7.getText();
        if(TxtRepuesto7.getText().length()==0){
            Repuesto7=null;
        }else{
            Repuesto7=TxtRepuesto7.getText();}
        
        String Repuesto8=TxtRepuesto8.getText();
        if(TxtRepuesto8.getText().length()==0){
            Repuesto8=null; 
        }else{
            Repuesto8=TxtRepuesto8.getText();}
        
        String Repuesto9=TxtRepuesto9.getText();
        if(TxtRepuesto9.getText().length()==0){
            Repuesto9=null;
        }else{
            Repuesto9=TxtRepuesto9.getText();}
        
        String Repuesto10=TxtRepuesto10.getText();
        if(TxtRepuesto10.getText().length()==0){
            Repuesto10=null; 
        }else{
            Repuesto10=TxtRepuesto10.getText();}
        
   //valores de los spinner que se ingresan como cantidad en la BD
        
       double cantidad1=Double.parseDouble(spinner1);
       double cantidad2=Double.parseDouble(spinner2);
       double cantidad3=Double.parseDouble(spinner3);
       double cantidad4=Double.parseDouble(spinner4);
       double cantidad5=Double.parseDouble(spinner5);
       double cantidad6=Double.parseDouble(spinner6);
       double cantidad7=Double.parseDouble(spinner7);
       double cantidad8=Double.parseDouble(spinner8);
       double cantidad9=Double.parseDouble(spinner9);
       double cantidad10=Double.parseDouble(spinner10);
   
       //multiplicamos el precio de las piezas por la cantidad de los spinners
       double costopieza1=Double.parseDouble(CostoPieza1.getText());
       double multicosto1=costopieza1 * cantidad1;
       
        double costopieza2=Double.parseDouble(CostoPieza2.getText());
       double multicosto2=costopieza2 * cantidad2;
       
       double costopieza3=Double.parseDouble(CostoPieza3.getText());
       double multicosto3=costopieza3 * cantidad3;
       
       double costopieza4=Double.parseDouble(CostoPieza4.getText());
       double multicosto4=costopieza4 * cantidad4;
       
       double costopieza5=Double.parseDouble(CostoPieza5.getText());
       double multicosto5=costopieza5 * cantidad5;
       
       double costopieza6=Double.parseDouble(CostoPieza6.getText());
       double multicosto6=costopieza6 * cantidad6;
       
       double costopieza7=Double.parseDouble(CostoPieza7.getText());
       double multicosto7=costopieza7 * cantidad7;
       
       double costopieza8=Double.parseDouble(CostoPieza8.getText());
       double multicosto8=costopieza8 * cantidad8;
       
       double costopieza9=Double.parseDouble(CostoPieza9.getText());
       double multicosto9=costopieza9 * cantidad9;
       
       double costopieza10=Double.parseDouble(CostoPieza10.getText());
       double multicosto10=costopieza10 * cantidad10;
       
//Sumamos el precio total de las pieza con el precio del servicio
double costoServicio=Double.parseDouble(TxtCosto.getText());
double costo_total=multicosto1+multicosto2+multicosto3+multicosto4+multicosto5+multicosto6+multicosto7+multicosto8+multicosto9+multicosto10+costoServicio;
Costo_total.setText(String.valueOf(costo_total));

          
        f.nuevoServicio(Campo1, Campo2, Repuesto1, spinner1,Repuesto2, spinner2,Repuesto3, spinner3,Repuesto4, spinner4,Repuesto5, spinner5,Repuesto6, spinner6,Repuesto7, spinner7,Repuesto8, spinner8,Repuesto9, spinner9,Repuesto10, spinner10,costo_total,costopieza1,costopieza2,costopieza3,costopieza4,costopieza5,costopieza6,
        costopieza7,costopieza8,costopieza9,costopieza10);
//        f.nuevoServicio(Campo1, Campo2, Repuesto1, Spinner1,Repuesto2,Spinner2,Repuesto3,Spinner3,Repuesto4,Spinner4,Repuesto5,Spinner5,Repuesto6,Spinner6,Repuesto7,Spinner7,Repuesto8,Spinner8,Repuesto9,Spinner9,Repuesto10,Spinner10);

        //id_cliente, nombre1, apellido_P2, apellido_M3, telefono4, TIF5, Email6, colonia7, calle8, no9, fecha10, hora11 
        //mostrarusuario();
       
        JOptionPane.showMessageDialog(rootPane,"Cliente ingresado");
//        System.out.print(jcodigo);
       
        mostrarServicio();
        mostrarDatos();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (fila > -1){
            String codigo = String.valueOf(TablaServicio1.getValueAt(fila, 0));                        
            f.eliminarServicio(codigo);
            mostrarServicio();
            mostrarDatos();
            fila=-1;
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

     String Campo1;
         //convetimos los valores del spinner en a String
       String spinner1 = jsCantidad1.getValue().toString();
       String spinner2 = jsCantidad2.getValue().toString();
       String spinner3 = jsCantidad3.getValue().toString();
       String spinner4 = jsCantidad4.getValue().toString();
       String spinner5 = jsCantidad5.getValue().toString();
       String spinner6 = jsCantidad6.getValue().toString();
       String spinner7 = jsCantidad7.getValue().toString();
       String spinner8 = jsCantidad8.getValue().toString();
       String spinner9 = jsCantidad9.getValue().toString();
       String spinner10 = jsCantidad10.getValue().toString();
       
      
       
        Campo1=TxtnombreServicio.getText();
        double Campo2=Double.parseDouble(TxtCosto.getText());
        
         ///VALIDAMOS LAS CAJAS DE TEXTO DE LOS REPUESTOS SI ESTAN VACIAS TIENE QUE ENVIAR UN NULL A LA BD
        String Repuesto1=TxtRepuesto1.getText();
        if(TxtRepuesto1.getText().length()==0){
            Repuesto1=null; 
        }else{
            Repuesto1=TxtRepuesto1.getText();}
        
        String Repuesto2=TxtRepuesto2.getText();
        if(TxtRepuesto2.getText().length()==0){
            Repuesto2=null;
        }else{
            Repuesto2=TxtRepuesto2.getText();}
        
        String Repuesto3=TxtRepuesto3.getText();
        if(TxtRepuesto3.getText().length()==0){
            Repuesto3=null;
        }else{
            Repuesto3=TxtRepuesto3.getText();}
        
        String Repuesto4=TxtRepuesto4.getText();
        if(TxtRepuesto4.getText().length()==0){
            Repuesto4=null;
       }else{
            Repuesto4=TxtRepuesto4.getText();}
        
        String Repuesto5=TxtRepuesto5.getText();
        if(TxtRepuesto5.getText().length()==0){
            Repuesto5=null;
        }else{
            Repuesto5=TxtRepuesto5.getText();}
        
        String Repuesto6=TxtRepuesto6.getText();
        if(TxtRepuesto6.getText().length()==0){
            Repuesto6=null;
        }else{
            Repuesto6=TxtRepuesto6.getText();}
        
        String Repuesto7=TxtRepuesto7.getText();
        if(TxtRepuesto7.getText().length()==0){
            Repuesto7=null;
        }else{
            Repuesto7=TxtRepuesto7.getText();}
        
        String Repuesto8=TxtRepuesto8.getText();
        if(TxtRepuesto8.getText().length()==0){
            Repuesto8=null; 
        }else{
            Repuesto8=TxtRepuesto8.getText();}
        
        String Repuesto9=TxtRepuesto9.getText();
        if(TxtRepuesto9.getText().length()==0){
            Repuesto9=null;
        }else{
            Repuesto9=TxtRepuesto9.getText();}
        
        String Repuesto10=TxtRepuesto10.getText();
        if(TxtRepuesto10.getText().length()==0){
            Repuesto10=null; 
        }else{
            Repuesto10=TxtRepuesto10.getText();}
        
//   //valores de los spinner que se ingresan como cantidad en la BD
//        
//       int cantidad1=Integer.parseInt(spinner1);
//       int cantidad2=Integer.parseInt(spinner2);
//       int cantidad3=Integer.parseInt(spinner3);
//       int cantidad4=Integer.parseInt(spinner4);
//       int cantidad5=Integer.parseInt(spinner5);
//       int cantidad6=Integer.parseInt(spinner6);
//       int cantidad7=Integer.parseInt(spinner7);
//       int cantidad8=Integer.parseInt(spinner8);
//       int cantidad9=Integer.parseInt(spinner9);
//       int cantidad10=Integer.parseInt(spinner10);
   
//enviamos el valor de la clave primaria

      int  idServicio=Integer.parseInt(TxtCodigoServicio.getText());
        f.ActualizarServicio(Campo1, Campo2, Repuesto1, spinner1,Repuesto2, spinner2,Repuesto3, spinner3,Repuesto4, spinner4,Repuesto5, spinner5,Repuesto6, spinner6,Repuesto7, spinner7,Repuesto8, spinner8,Repuesto9, spinner9,Repuesto10, spinner10,idServicio);
//        f.nuevoServicio(Campo1, Campo2, Repuesto1, Spinner1,Repuesto2,Spinner2,Repuesto3,Spinner3,Repuesto4,Spinner4,Repuesto5,Spinner5,Repuesto6,Spinner6,Repuesto7,Spinner7,Repuesto8,Spinner8,Repuesto9,Spinner9,Repuesto10,Spinner10);

        //id_cliente, nombre1, apellido_P2, apellido_M3, telefono4, TIF5, Email6, colonia7, calle8, no9, fecha10, hora11 
        //mostrarusuario();
       
        JOptionPane.showMessageDialog(rootPane,"Cliente ingresado");
//        System.out.print(jcodigo);
       
        mostrarServicio();
mostrarDatos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void TxtnombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnombreServicioActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mostrarServicio();
mostrarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void TablaServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaServicioMouseClicked
fila = TablaServicio.rowAtPoint(evt.getPoint());

         if (fila > -1){                          
             TxtCodigoServicio.setText(String.valueOf(TablaServicio1.getValueAt(fila, 0)));
             TxtnombreServicio.setText(String.valueOf(TablaServicio1.getValueAt(fila, 1)));
             TxtCosto.setText(String.valueOf(TablaServicio1.getValueAt(fila, 2)));
             
             //vaciamos las cajas de texto en caso de que la BD devuelva nullo
             if(TablaServicio1.getValueAt(fila, 3)==null){  
               TxtRepuesto1.setText("");
               jsCantidad1.setValue(0);
                
             }else{
                 TxtRepuesto1.setText(String.valueOf(TablaServicio1.getValueAt(fila, 3)));  
                 String cantidad1 = String.valueOf(TablaServicio1.getValueAt(fila, 4));
             int Cantidad1 = Integer.parseInt(cantidad1);
             jsCantidad1.setValue(Cantidad1);
             CostoPieza1.setText(String.valueOf(TablaServicio1.getValueAt(fila, 24)));
             }
             
              if(TablaServicio1.getValueAt(fila, 5)==null){  
               TxtRepuesto2.setText("");
               jsCantidad2.setValue(0);
             }else{
             TxtRepuesto2.setText(String.valueOf(TablaServicio1.getValueAt(fila, 5)));
             String cantidad2 = String.valueOf(TablaServicio1.getValueAt(fila, 6));
             int Cantidad2 = Integer.parseInt(cantidad2);
             jsCantidad2.setValue(Cantidad2);
             CostoPieza2.setText(String.valueOf(TablaServicio1.getValueAt(fila, 25)));
             }
              
               if(TablaServicio1.getValueAt(fila, 7)==null){  
               TxtRepuesto3.setText("");
               jsCantidad3.setValue(0);
             }else{
             TxtRepuesto3.setText(String.valueOf(TablaServicio1.getValueAt(fila, 7)));
             String cantidad3 = String.valueOf(TablaServicio1.getValueAt(fila, 8));
             int Cantidad3 = Integer.parseInt(cantidad3);
             jsCantidad3.setValue(Cantidad3);
             CostoPieza3.setText(String.valueOf(TablaServicio1.getValueAt(fila, 26)));
             }
               
                if(TablaServicio1.getValueAt(fila, 9)==null){  
               TxtRepuesto4.setText("");
               jsCantidad4.setValue(0);
             }else{
             TxtRepuesto4.setText(String.valueOf(TablaServicio1.getValueAt(fila, 9)));
             String cantidad4 = String.valueOf(TablaServicio1.getValueAt(fila, 10));
             int Cantidad4 = Integer.parseInt(cantidad4);
             jsCantidad4.setValue(Cantidad4);
             CostoPieza4.setText(String.valueOf(TablaServicio1.getValueAt(fila, 27)));
             }
                
                 if(TablaServicio1.getValueAt(fila,11)==null){  
               TxtRepuesto5.setText("");
               jsCantidad5.setValue(0);
             }else{
             TxtRepuesto5.setText(String.valueOf(TablaServicio1.getValueAt(fila, 11)));
             String cantidad5 = String.valueOf(TablaServicio1.getValueAt(fila, 12));
             int Cantidad5 = Integer.parseInt(cantidad5);
             jsCantidad5.setValue(Cantidad5);
              CostoPieza5.setText(String.valueOf(TablaServicio1.getValueAt(fila, 28)));

             }
            
             if (TablaServicio1.getValueAt(fila, 13) == null) {
                 TxtRepuesto6.setText("");
                 jsCantidad6.setValue(0);
             } else {
             TxtRepuesto6.setText(String.valueOf(TablaServicio1.getValueAt(fila, 13)));
             String cantidad6 = String.valueOf(TablaServicio1.getValueAt(fila, 14));
             int Cantidad6 = Integer.parseInt(cantidad6);
             jsCantidad6.setValue(Cantidad6);
              CostoPieza6.setText(String.valueOf(TablaServicio1.getValueAt(fila, 29)));
             }
             
             if (TablaServicio1.getValueAt(fila, 15) == null) {
                 TxtRepuesto7.setText("");
                 jsCantidad7.setValue(0);
             } else {
             TxtRepuesto7.setText(String.valueOf(TablaServicio1.getValueAt(fila, 15)));
             String cantidad7 = String.valueOf(TablaServicio1.getValueAt(fila, 16));
             int Cantidad7 = Integer.parseInt(cantidad7);
             jsCantidad7.setValue(Cantidad7);
              CostoPieza7.setText(String.valueOf(TablaServicio1.getValueAt(fila, 30)));
             }
             
             if (TablaServicio1.getValueAt(fila, 17) == null) {
                 TxtRepuesto8.setText("");
                 jsCantidad8.setValue(0);
             } else {
             TxtRepuesto8.setText(String.valueOf(TablaServicio1.getValueAt(fila, 17)));
             String cantidad8 = String.valueOf(TablaServicio1.getValueAt(fila, 18));
             int Cantidad8 = Integer.parseInt(cantidad8);
             jsCantidad8.setValue(Cantidad8);
              CostoPieza8.setText(String.valueOf(TablaServicio1.getValueAt(fila, 31)));
             }
             
             if (TablaServicio1.getValueAt(fila, 19) == null) {
                 TxtRepuesto9.setText("");
                 jsCantidad9.setValue(0);
             } else {
             TxtRepuesto9.setText(String.valueOf(TablaServicio1.getValueAt(fila, 19)));
             String cantidad9 = String.valueOf(TablaServicio1.getValueAt(fila, 20));
             int Cantidad9 = Integer.parseInt(cantidad9);
             jsCantidad9.setValue(Cantidad9);
              CostoPieza9.setText(String.valueOf(TablaServicio1.getValueAt(fila, 32)));
             }
             
             if (TablaServicio1.getValueAt(fila, 21) == null) {
                 TxtRepuesto10.setText("");
                 jsCantidad10.setValue(0);
             } else {
             TxtRepuesto10.setText(String.valueOf(TablaServicio1.getValueAt(fila, 21)));
              String cantidad10 = String.valueOf(TablaServicio1.getValueAt(fila, 22));
             int Cantidad10 = Integer.parseInt(cantidad10);
             jsCantidad10.setValue(Cantidad10);
              CostoPieza10.setText(String.valueOf(TablaServicio1.getValueAt(fila, 33)));
             }
             
             
             CostoPieza10.setText(String.valueOf(TablaServicio1.getValueAt(fila, 33)));
             Costo_total.setText(String.valueOf(TablaServicio1.getValueAt(fila, 23)));

             
             
             

             
             
             
             
             
             
            

            
             
//             "idservicio","nombre_servicio", "costo_servicio", "cantidad", "nombre_REpuesto","id_Repuesto"
             
        
         
        
         
        
         
        
         
        
         
        
        
        
//System.out.print(TablaServicio1.getValueAt(fila, 5));
         }


                
    }//GEN-LAST:event_TablaServicioMouseClicked

    private void BtnRepuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto1ActionPerformed

    new inventario().setVisible(true);
    inventario.opc = 1;
    
   inventario.TxtVerficaVentana.setText("1");
    
    }//GEN-LAST:event_BtnRepuesto1ActionPerformed

    private void TxtRepuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto2ActionPerformed
      
        
// TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto2ActionPerformed

    private void BtnRepuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto2ActionPerformed
      new inventario().setVisible(true);
      inventario.opc = 2;
    
   inventario.TxtVerficaVentana.setText("1");
    }//GEN-LAST:event_BtnRepuesto2ActionPerformed

    private void TxtRepuesto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto3ActionPerformed

    private void BtnRepuesto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto3ActionPerformed
new inventario().setVisible(true);
      inventario.opc = 3;
    
   inventario.TxtVerficaVentana.setText("1");     
    }//GEN-LAST:event_BtnRepuesto3ActionPerformed

    private void TxtRepuesto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto4ActionPerformed

    private void BtnRepuesto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto4ActionPerformed
       
        new inventario().setVisible(true);
      inventario.opc = 4;
    
   inventario.TxtVerficaVentana.setText("1"); 
    }//GEN-LAST:event_BtnRepuesto4ActionPerformed

    private void TxtRepuesto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto5ActionPerformed

    private void BtnRepuesto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto5ActionPerformed
new inventario().setVisible(true);
      inventario.opc = 5;
    
   inventario.TxtVerficaVentana.setText("1"); 


    }//GEN-LAST:event_BtnRepuesto5ActionPerformed

    private void TxtRepuesto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto6ActionPerformed

    private void BtnRepuesto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto6ActionPerformed
new inventario().setVisible(true);
      inventario.opc = 6;
    
   inventario.TxtVerficaVentana.setText("1"); 
    }//GEN-LAST:event_BtnRepuesto6ActionPerformed

    private void TxtRepuesto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto7ActionPerformed

    }//GEN-LAST:event_TxtRepuesto7ActionPerformed

    private void BtnRepuesto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto7ActionPerformed
new inventario().setVisible(true);
      inventario.opc = 7;
    
   inventario.TxtVerficaVentana.setText("1"); 
    }//GEN-LAST:event_BtnRepuesto7ActionPerformed

    private void BtnRepuesto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto8ActionPerformed
       new inventario().setVisible(true);
      inventario.opc = 8;
    
   inventario.TxtVerficaVentana.setText("1"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRepuesto8ActionPerformed

    private void TxtRepuesto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto8ActionPerformed

    private void BtnRepuesto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto9ActionPerformed
new inventario().setVisible(true);
      inventario.opc = 9;
    
   inventario.TxtVerficaVentana.setText("1"); 
    }//GEN-LAST:event_BtnRepuesto9ActionPerformed

    private void TxtRepuesto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto9ActionPerformed

    private void BtnRepuesto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepuesto10ActionPerformed
new inventario().setVisible(true);
      inventario.opc =10 ;
    
   inventario.TxtVerficaVentana.setText("1"); 
    }//GEN-LAST:event_BtnRepuesto10ActionPerformed

    private void TxtRepuesto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepuesto10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepuesto10ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();
    new Inicio().setVisible(true);
            
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
         switch(opcServicio){
            case 1:
            //fila = TablaCliente.rowAtPoint(evt.getPoint());
            //            if (fila > -1){
                //               Servicio.jcodigo1.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 0)));
                //               Servicio.TxtRepuesto1.setText(String.valueOf(Tabla_Invenatrio1.getValueAt(fila, 2)));
                //            }
            //Asignacion_Servicio.TxtCodigoServicio.setText(TxtCodigoServicio.getText());
            Asignacion_Servicio.txtServico.setText(TxtnombreServicio.getText());
            Asignacion_Servicio.txtCosto.setText(Costo_total.getText());

            this.dispose();
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnRepuesto1;
    private javax.swing.JButton BtnRepuesto10;
    private javax.swing.JButton BtnRepuesto2;
    private javax.swing.JButton BtnRepuesto3;
    private javax.swing.JButton BtnRepuesto4;
    private javax.swing.JButton BtnRepuesto5;
    private javax.swing.JButton BtnRepuesto6;
    private javax.swing.JButton BtnRepuesto7;
    private javax.swing.JButton BtnRepuesto8;
    private javax.swing.JButton BtnRepuesto9;
    public static javax.swing.JLabel CostoPieza1;
    public static javax.swing.JLabel CostoPieza10;
    public static javax.swing.JLabel CostoPieza2;
    public static javax.swing.JLabel CostoPieza3;
    public static javax.swing.JLabel CostoPieza4;
    public static javax.swing.JLabel CostoPieza5;
    public static javax.swing.JLabel CostoPieza6;
    public static javax.swing.JLabel CostoPieza7;
    public static javax.swing.JLabel CostoPieza8;
    public static javax.swing.JLabel CostoPieza9;
    private javax.swing.JLabel Costo_total;
    private javax.swing.JTable TablaServicio;
    private javax.swing.JTable TablaServicio1;
    private javax.swing.JLabel TxtCodigoServicio;
    private javax.swing.JTextField TxtCosto;
    public static javax.swing.JTextField TxtRepuesto1;
    public static javax.swing.JTextField TxtRepuesto10;
    public static javax.swing.JTextField TxtRepuesto2;
    public static javax.swing.JTextField TxtRepuesto3;
    public static javax.swing.JTextField TxtRepuesto4;
    public static javax.swing.JTextField TxtRepuesto5;
    public static javax.swing.JTextField TxtRepuesto6;
    public static javax.swing.JTextField TxtRepuesto7;
    public static javax.swing.JTextField TxtRepuesto8;
    public static javax.swing.JTextField TxtRepuesto9;
    private javax.swing.JTextField TxtnombreServicio;
    public static javax.swing.JLabel VerificaServicio;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel jcodigo1;
    public static javax.swing.JLabel jcodigo10;
    public static javax.swing.JLabel jcodigo2;
    public static javax.swing.JLabel jcodigo3;
    public static javax.swing.JLabel jcodigo4;
    public static javax.swing.JLabel jcodigo5;
    public static javax.swing.JLabel jcodigo6;
    public static javax.swing.JLabel jcodigo7;
    public static javax.swing.JLabel jcodigo8;
    public static javax.swing.JLabel jcodigo9;
    public static javax.swing.JSpinner jsCantidad1;
    public static javax.swing.JSpinner jsCantidad10;
    public static javax.swing.JSpinner jsCantidad2;
    public static javax.swing.JSpinner jsCantidad3;
    public static javax.swing.JSpinner jsCantidad4;
    public static javax.swing.JSpinner jsCantidad5;
    public static javax.swing.JSpinner jsCantidad6;
    public static javax.swing.JSpinner jsCantidad7;
    public static javax.swing.JSpinner jsCantidad8;
    public static javax.swing.JSpinner jsCantidad9;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
